services:
  - type: web
    name: cyber-threat-dashboard
    env: python
    buildCommand: |
      curl -sSL https://install.python-poetry.org | python3 -
      python3 -m venv venv
      . venv/bin/activate
      python --version
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: VT_API_KEY
        sync: false
      - key: ABUSE_API_KEY
        sync: false
